config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as:"task"

  post "tasks", to: "tasks#create"

  get "tasks/:id/edit", to: "tasks#edit", as: :edit

  patch "tasks/:id", to: "tasks#update"

  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

   def create
    @task = Task.new(params[:task])
    @restaurant.save

  end

  def edit
    @task = Task.find(params[:id])
  end

  def show
    @task = Task.find(params[:id])
  end

  def update
  @task = Task.find(params[:id])
  @task.update[params[:task]]
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>EDIT TASK</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

    <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>



<p>
<%= link_to "RETOUR A LA LISTE", tasks_path %>
</p>

app/views/tasks/index.html.erb
<h1>Task list</h1>

<ul>
  <% @tasks.each do |task| %>
    <li> <%=link_to task.title, task_path(task)%>
    </li>
    <INPUT type="checkbox" name="choix1" value="1">

  <%end%>

</ul>

<%= link_to "Add a task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>NEW TASK</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

    <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>





<p>
<%= link_to "RETOUR A LA LISTE", tasks_path %>
</p>

app/views/tasks/show.html.erb
<h1>Task Selected</h1>

<h2><%= @task.title %></h2>

<%= link_to "RETOUR A LA LISTE", tasks_path %>


<%= link_to "Editer", edit_path %>